import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCartShopping, faPhone, faBars} from "@fortawesome/free-solid-svg-icons";
import { fab, faTwitter, faFacebookF , faFacebook, faLinkedin ,faFlickr} from '@fortawesome/free-brands-svg-icons';
import {faEnvelope} from "@fortawesome/free-regular-svg-icons";
import {faXmark} from "@fortawesome/free-solid-svg-icons";


library.add(
    faCartShopping,
    faEnvelope,
    faPhone,
    faXmark,
    faBars,
    fab,
    faTwitter,
    faFacebook,
    faFacebookF,
    faLinkedin,
    faFlickr
);
export default function Home() {
  return (
    <div className="h-[200px]">
      <Head>
        <title>Nationwide Surveyors | All Landlord Certifications Offered at One Place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
