import Head from "next/head";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faBars,
  faCartShopping,
  faChevronDown,
  faChevronRight, faCircleDot, faLocationCrosshairs,
  faPhone,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import {
  fab,
  faFacebook,
  faFacebookF,
  faFlickr,
  faLinkedin,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import { faEnvelope } from "@fortawesome/free-regular-svg-icons";
import HomeTab from "../components/homeTabs.component";
import SelectProperty from "../components/selectProperty.component";
import Pricing from "../components/pricing.component";
import PricingCarouselComponent from "../components/pricingCarousel.component";
import { DeviceContext } from "../components/deviceContext.component";
import React, { useContext } from "react";
import ServiceInfo from "../components/serviceInfo.component";
import { homeServices, howItWorks, ourServices } from "../utility/constants";
import OurServicesComponent from "../components/ourServices.component";
import HowItWorks from "../components/howItWorksCard.component";
import StepperComponent from "../components/stepper.component";
import ButtonComponent from "../components/button.component";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import CarouselComponent from "../components/carousel.component";
import {useRouter} from "next/router";
import BoxBackgroundComponent from "../components/boxBackground.component";

library.add(
  faCartShopping,
  faEnvelope,
  faPhone,
  faXmark,
  faChevronDown,
  faBars,
  fab,
  faTwitter,
  faFacebook,
  faFacebookF,
  faLinkedin,
  faFlickr,
  faChevronRight
);
export default function Home() {
  const { smallDevice, middleDevice, largeDevice }: any =
    useContext(DeviceContext);
  const router = useRouter();
  return (
    <div className="ml-auto mr-auto">
      <Head>
        <title>Landlord Certifications | Nationwide Surveyors</title>
        <meta
          name="Nationwide Surveyors"
          content="Generated by create next app"
        />
      </Head>
      <div className="w-full bg-white lg:min-h-[530px] lg:px-10 pt-[40px] flex flex-wrap justify-around ">
            <div className="w-full mt-4 lg:mt-0 bg-dark-blue order-2 mx-auto lg:bg-white md:order-1 lg:w-[63.5%] xl:w-[62.4%]">
              <HomeTab />
            </div>
            <div className="lg:order-2 w-[95%] lg:w-[27.5%] xl:w-[26.7%] ">
              <SelectProperty />
            </div>
      </div>
      <BoxBackgroundComponent className='h-[700px] pt-5'
        greyStyle='w-[60%] h-[50%] md:w-[40%]'
        limeStyle='right-0 bottom-0 w-[60%] h-[40%] md:w-[40%]'
      >
        <div className='w-full py-5 mt-3 lg:min-[970px] xl:min-w-[1170px] xl:max-w-[1170px] mx-auto'>
          <div className='px-2 ml-4 md:ml-0'>
            <div className='border-[2px] w-[70px] rounded-full mt-2 mb-1 md:w-28 border-lime'/>
            <h2 className='text-[18px] font-semibold md:text-[30px] mb-4'>Services Bundle Offers</h2>
          </div>
          <PricingCarouselComponent />
          <Pricing />
        </div>
      </BoxBackgroundComponent>

        <div className="w-full py-5 lg:min-[950px] xl:min-w-[1170px] xl:max-w-[1170px] mx-auto">
            <div className="w-full flex flex-row ">
              <div className="flex flex-col justify-between items-center py-5">
                <div className="w-[1px] items-center justify-between py-10 flex flex-col bg-dark-blue h-full">
                  <div className="bg-lime rounded-full w-[5px] h-[8%]"></div>
                  <div className="bg-lime rounded-full w-[5px] h-[8%]"></div>
                  <div className="bg-lime rounded-full w-[5px] h-[8%]"></div>
                  <div className="bg-lime rounded-full w-[5px] h-[8%]"></div>
                </div>
              </div>
                <div className="flex flex-col items-center justify-center px-3 ">
                  {homeServices.map(({ className, content }: any, index: any) => {
                    return (
                      <div
                        className={`${
                          index % 2 == 0
                            ? "flex-col lg:flex-row"
                            : "flex-col-reverse  lg:flex-row-reverse"
                        } pb-[60px] flex gap-6`}
                        key={index}
                      >
                        <ServiceInfo content={content} className={className} />
                      </div>
                    );
                  })}
              </div>
            </div>
        </div>
          {/*ALL OUR SERVICES*/}
          <div className="w-full py-5 lg:min-[970px] xl:min-w-[1170px] xl:max-w-[1170px] mx-auto">
          <section>
            <div className="w-full flex flex-col items-start md:items-center justify-center px-3">
              <div className="w-full md:container flex flex-wrap pb-[60px]">
                <div className="mb-[30px] pr-5 py-2">
                  <div className='border-lime border-b-4 rounded-full w-[40%] mb-3'></div>
                  <h2 className="text-dark-blue text-4xl font-medium font-bold">
                    All Our Services
                  </h2>
                </div>
                <div className=" hidden lg:flex lg:gap-2 xl:gap-6 xxl:gap-9">
                  {ourServices.map(({ list, title, image }, index) => {
                    return (
                        <OurServicesComponent
                            key={index}
                            list={list}
                            title={title}
                            image={image}
                        />
                    );
                  })}
                </div>
                <div className="lg:hidden w-full">
                  <CarouselComponent
                      list={ourServices}
                      component={OurServicesComponent}
                      className="h-[420px]"
                  />
                </div>
              </div>
            </div>
          </section>

          {/*HOW IT WORKS*/}

          <section>
            <div className="w-full flex flex-col items-center justify-center px-3">
              <div className="  w-full md:container flex flex-col flex-wrap pb-[0px]">
                <div className=" border-lime mb-[30px] py-2">
                  <div className="border-b-4 border-lime rounded-full w-[85px] mb-3"></div>
                  <h2 className="text-dark-blue text-4xl font-medium font-bold">
                    How it works?
                  </h2>
                </div>
                {/*<StepperComponent />*/}
                <div className="hidden mt-10 w-full md:flex  justify-center xl:flex-nowrap gap-1 xl:gap-7">
                  {howItWorks.map(({ title, paragraph, image }: any, index) => {
                    return (
                        <HowItWorks
                            key={index}
                            title={title}
                            paragraph={paragraph}
                            index={index}
                            type="Home"
                            image={image}
                        />
                    );
                  })}
                </div>
                <div className="flex mt-10  md:hidden w-full h-[300px] justify-center xl:flex-nowrap gap-1 xl:gap-7">
                  <CarouselComponent list={howItWorks} component={HowItWorks} className='min-h-520px '/>
                </div>
              </div>
            </div>
          </section>
        </div>
      {/*B2B SECTION*/}
      <section>
        <div className="w-full flex justify-center">
          <div className="w-full lg:min-[970px] xl:min-w-[1170px] xl:max-w-[1170px] mx-auto px-3">
            <div className="w-full flex flex-row justify-between items-start flex-wrap pt-[80px] pb-[60px]">
              <div className="flex flex-col border-white mb-[30px] py-2">
                <div className='border-b-4 border-lime rounded-full w-[70px] mb-3'></div>
                <h4 className="text-sm mb-[2px] mt-[5px] uppercase font-semibold text-dark-blue tracking-[1px]">
                  Placing Repeat Orders ?
                </h4>
                <h2 className="text-4xl text-dark-blue font-semibold">
                  Why Not Join Our B2B
                  Service
                </h2>
                  <div className="hidden w-[60%] lg:flex ">
                    <ButtonComponent
                        text="Instant Quote and order here"
                        className="w-full flex mt-5  bg-lime self-start font-semibold uppercase items-center justify-center hover:bg-dark-blue hover:text-white px-[28px] py-[12px] text-sm ease-in duration-200"
                        type="button"
                        onClick={() =>{
                          router?.push({
                            pathname: "/order-now",
                          });}
                        }
                    >
                    </ButtonComponent>
                  </div>
                </div>
              <div className="w-full self-center xl:w-[44%]">
                <p className="text-dark-blue text-[15px] leading-[27px]">
                  For those customers needing to make regular orders you can get
                  direct access to our bespoke order management system for live
                  updates.We offer a fully national service and can provide
                  EPCs, Electrical Reports, Gas Safety Certificates plus many
                  additional services.
                </p>
              </div>
            </div>
            <div className="mb-5 lg:hidden">
              <ButtonComponent
                  text="Instant Quote and order here"
                  className="w-full flex  bg-lime self-start font-semibold uppercase items-center justify-center hover:bg-dark-blue hover:text-white px-[28px] py-[12px] text-sm ease-in duration-200"
                  type="button"
                  onClick={() =>{
                    router?.push({
                      pathname: "/order-now",
                    });}
                  }
              >
              </ButtonComponent>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
}
